# permissions to do viewer frigates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: frigate-viewer-role
rules:
- apiGroups:
  - ship.example.com
  resources:
  - frigates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ship.example.com
  resources:
  - frigates/status
  verbs:
  - get
