# permissions to do edit frigates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: frigate-editor-role
rules:
- apiGroups:
  - ship.example.com
  resources:
  - frigates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ship.example.com
  resources:
  - frigates/status
  verbs:
  - get
  - patch
  - update
